title: vinv.io 
email: support@vinv.io
description: Lightweight data standard and structure for single-tree based forest management, visualization & analytics


baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://vinv.io" # the base hostname & protocol for your site, e.g. http://example.com
name: "Virtual Inventory"
lang: "en"
tags: "forestry, inventory, vinv, standard, exchange"